#include <iostream>
#include <bitset>
#include <fstream>
#include <vector>

// TODO ensure comptibility with file formates other than text
//EVIL BIT LEVEL HACKING

using namespace std;

/*
 * flips bits for the file based on a random number generated by a password used as a seed
 * TODO flips bits for the file based on a random number generated by a password used as a seed
 */

void encrypt(vector<string> &lines){
	string currLine;

	for (auto &line : lines) {
		currLine = line;

		for (char &jj : currLine) {
			bitset<8> bitset(jj);

			for (int k = 0; k < 8; k++){
				bitset[k] = !bitset[k];
			}

			jj = char(bitset.to_ullong());
		}
		line = currLine;
	}
}

/*
 * opens a file and reads every line into a vector
 */

void read(vector<string> &lines, string source){
	string l;
	fstream target;
	target.open(source);

	while(getline(target,l)){
		cout << l << endl;
		lines.push_back(l);
	}

	target.close();
}

/*
 * writes to the source file with the encrypted or decrypted info
 */

void write(vector<string> &lines, string source){
	fstream target;
	target.open(source);

	for (const auto &line : lines) {
		target << line << endl;
	}

	target.close();
}

int main() {

	vector<string> lines;
	string source;

	cout << "Enter the target file" << endl;
	cin >> source;

	read(lines, source);

	encrypt(lines);

	write(lines, source);

	return 0;
}